default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  password: <%= ENV.fetch("DB_PASSWORD") { 'password' } %>

development:
  <<: *default
  database: himatsubushi_manual_development

test:
  <<: *default
  database: himatsubushi_manual_test

production:
  <<: *default
  database: himatsubushi_manual_production
  username: himatsubushi_manual
